package com.model;

/**
 * TGongzi generated by MyEclipse Persistence Tools
 */

public class TGongzi implements java.io.Serializable
{

	private Integer id;
	private Integer yuangongId;
	private String yuefen;
	private Integer jibengongzi;

	private Integer jiabanfei;
	private Integer jiangjin;
	private Integer qingjiafei;
	private Integer shifagongzi;
	
	private TYuangong yuangong;

	public Integer getId()
	{
		return id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public Integer getJiabanfei()
	{
		return jiabanfei;
	}

	public void setJiabanfei(Integer jiabanfei)
	{
		this.jiabanfei = jiabanfei;
	}

	public Integer getJiangjin()
	{
		return jiangjin;
	}

	public void setJiangjin(Integer jiangjin)
	{
		this.jiangjin = jiangjin;
	}

	public Integer getJibengongzi()
	{
		return jibengongzi;
	}

	public void setJibengongzi(Integer jibengongzi)
	{
		this.jibengongzi = jibengongzi;
	}

	public Integer getQingjiafei()
	{
		return qingjiafei;
	}

	public void setQingjiafei(Integer qingjiafei)
	{
		this.qingjiafei = qingjiafei;
	}

	public Integer getShifagongzi()
	{
		return shifagongzi;
	}

	public void setShifagongzi(Integer shifagongzi)
	{
		this.shifagongzi = shifagongzi;
	}

	public TYuangong getYuangong()
	{
		return yuangong;
	}

	public void setYuangong(TYuangong yuangong)
	{
		this.yuangong = yuangong;
	}

	public Integer getYuangongId()
	{
		return yuangongId;
	}

	public void setYuangongId(Integer yuangongId)
	{
		this.yuangongId = yuangongId;
	}

	public String getYuefen()
	{
		return yuefen;
	}

	public void setYuefen(String yuefen)
	{
		this.yuefen = yuefen;
	}
	

}