package com.model;

/**
 * TQiandao generated by MyEclipse Persistence Tools
 */

public class TQiandao implements java.io.Serializable
{

	private Integer id;
	private Integer yuangongId;
	private String riqi;
	private String shijian;

	private String shuxing;
	private TYuangong yuangong;
	
	private String qiantuishi;
	private String qiantuishuxing;
	
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public Integer getYuangongId() {
		return yuangongId;
	}
	public void setYuangongId(Integer yuangongId) {
		this.yuangongId = yuangongId;
	}
	public String getRiqi() {
		return riqi;
	}
	public void setRiqi(String riqi) {
		this.riqi = riqi;
	}
	public String getShijian() {
		return shijian;
	}
	public void setShijian(String shijian) {
		this.shijian = shijian;
	}
	public String getShuxing() {
		return shuxing;
	}
	public void setShuxing(String shuxing) {
		this.shuxing = shuxing;
	}
	public TYuangong getYuangong() {
		return yuangong;
	}
	public void setYuangong(TYuangong yuangong) {
		this.yuangong = yuangong;
	}
	public String getQiantuishi() {
		return qiantuishi;
	}
	public void setQiantuishi(String qiantuishi) {
		this.qiantuishi = qiantuishi;
	}
	public String getQiantuishuxing() {
		return qiantuishuxing;
	}
	public void setQiantuishuxing(String qiantuishuxing) {
		this.qiantuishuxing = qiantuishuxing;
	}
}