package com.model;

/**
 * TQingjia generated by MyEclipse Persistence Tools
 */

public class TQingjia implements java.io.Serializable
{

	private Integer id;
	private Integer yuangongId;
	private String kaishishijian;
	private String jieshushijian;
	
	private String shiyou;
	private String zt;//µÈ´ýÉóºË===ÉóºËÍ¨¹ý===ÉóºËÎ´¹ý
	private String shenheshijian;
	private String huifuxinxi;
	
    private TYuangong yuangong;

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public Integer getYuangongId()
	{
		return this.yuangongId;
	}

	public void setYuangongId(Integer yuangongId)
	{
		this.yuangongId = yuangongId;
	}

	public String getKaishishijian()
	{
		return this.kaishishijian;
	}

	public void setKaishishijian(String kaishishijian)
	{
		this.kaishishijian = kaishishijian;
	}

	public String getJieshushijian()
	{
		return this.jieshushijian;
	}

	public void setJieshushijian(String jieshushijian)
	{
		this.jieshushijian = jieshushijian;
	}

	public String getShiyou()
	{
		return this.shiyou;
	}

	public void setShiyou(String shiyou)
	{
		this.shiyou = shiyou;
	}

	public TYuangong getYuangong()
	{
		return yuangong;
	}

	public String getZt()
	{
		return zt;
	}

	public void setZt(String zt)
	{
		this.zt = zt;
	}

	public String getHuifuxinxi()
	{
		return huifuxinxi;
	}

	public void setHuifuxinxi(String huifuxinxi)
	{
		this.huifuxinxi = huifuxinxi;
	}

	public String getShenheshijian()
	{
		return shenheshijian;
	}

	public void setShenheshijian(String shenheshijian)
	{
		this.shenheshijian = shenheshijian;
	}

	public void setYuangong(TYuangong yuangong)
	{
		this.yuangong = yuangong;
	}

}